openapi: "3.0.1"
info:
  title: "Forbes-List"
  description: "Contains the list of the richest people"
  version: "2022-08-20T10:51:54Z"
servers:
- url: "https://mf3h40dbi7.execute-api.ap-south-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/production"
paths:
  /forbeslist:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
